// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kDebugMode, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcGcBPg_-qr6rLLYNHJ-O0MHBT4KCZ1ZI',
    appId: '1:1059012195244:web:0f090a45bf57d939e48009',
    messagingSenderId: '1059012195244',
    projectId: 'paradigm-mx',
    authDomain: 'paradigm-mx.firebaseapp.com',
    storageBucket: 'paradigm-mx.appspot.com',
    measurementId: 'G-5Q0XXQ1L6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpsLVg0FaX-b7Jz7GP3_sQUrJcrnumxTo',
    appId: '1:1059012195244:android:e75da62d528f48a8e48009',
    messagingSenderId: '1059012195244',
    projectId: 'paradigm-mx',
    storageBucket: 'paradigm-mx.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtF2jYMP3552ZAHYGx8EMLihFB_KQ9zvI',
    appId: '1:1059012195244:ios:11c046b5cbf44907e48009',
    messagingSenderId: '1059012195244',
    projectId: 'paradigm-mx',
    storageBucket: 'paradigm-mx.appspot.com',
    iosClientId:
        '1059012195244-tpjmveggd2dob2itgjbf2hlv21b5d08c.apps.googleusercontent.com',
    iosBundleId: 'com.paradigmmex.hunt',
  );

  static const FirebaseOptions webDev = FirebaseOptions(
    apiKey: 'AIzaSyDJ96QCIyk5LtqWQio8jtakoGfTHypdQ0M',
    appId: '1:443623361360:web:2de179e9e7d778e4dd7a55',
    messagingSenderId: '443623361360',
    projectId: 'paradigm-mx-development',
    authDomain: 'paradigm-mx-development.firebaseapp.com',
    storageBucket: 'paradigm-mx-development.appspot.com',
    measurementId: 'G-HGMNMGF934',
  );

  static const FirebaseOptions androidDev = FirebaseOptions(
    apiKey: 'AIzaSyCZWoqHWNDdwnD4HkYLY4XeLncjMjDvLU4',
    appId: '1:443623361360:android:f25c90b31d481e9add7a55',
    messagingSenderId: '443623361360',
    projectId: 'paradigm-mx-development',
    storageBucket: 'paradigm-mx-development.appspot.com',
  );

  static const FirebaseOptions iosDev = FirebaseOptions(
    apiKey: 'AIzaSyBjkrHg2rOI_ISQCMMCrp1dqKWY_0HFh0w',
    appId: '1:443623361360:ios:6389da2cf8126974dd7a55',
    messagingSenderId: '443623361360',
    projectId: 'paradigm-mx-development',
    storageBucket: 'paradigm-mx-development.appspot.com',
    iosClientId:
        '443623361360-j8e50873b8e5ll5jf7fa7o6psc58th13.apps.googleusercontent.com',
    iosBundleId: 'com.paradigmmex.hunt',
  );
}
